version: "3.8"

services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3307:3306
    environment:
      TZ: Asia/Seoul
    env_file: .env
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
